apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-registry-credentials
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registryCredentials }}